### PR TITLE
Enable Monad for array and object resolver

### PR DESCRIPTION
**Pull request by Lupino**
When I use facebook/haxl, I can not find any way to the sub resolver.
so I add Monad resolver to support it.

### CODE REVIEW

**Comment by Lupino** [comment]
Support facebook/haxl, just instance Alternative (GenHaxl u)
```haskell 
import           Control.Applicative
import           Control.Exception   (SomeException)
import           Haxl.Core           (CriticalError (..), GenHaxl, catch, throw)
import           Prelude             hiding (catch, empty)
catchAny
  :: GenHaxl u a   -- ^ run this first
  -> GenHaxl u a   -- ^ if it throws 'LogicError' or 'TransientError', run this
  -> GenHaxl u a
catchAny haxl handler =
  haxl `catch` \(e :: SomeException) -> handler

instance Alternative (GenHaxl u) where
  a <|> b = catchAny a b
  empty = throw $ CriticalError "mzero"
```

**Comment by Lupino** [comment]
https://github.com/Lupino/coin/blob/mysql/src/Coin/GraphQL.hs  example code here

**Comment by jdnavarro** [comment]
Now that I see your code, I think it should be possible to modify the existing Schema functions to cover your use case. Adding the `Monad` constrain is a no brainer, at some point I'd have to do it anyway, but I was wondering about the argument with the list of resolvers wrapped in `Alternative`, i. e: `f [Resolver f]`. Is the wrapping really necessary for you?

BTW, even if there is a way to define schema, it's still not possible to use it for an actual execution. Hopefully, it'll be possible soon.

**Comment by Lupino** [comment]
Yes. The wrapped `f [Resolver f]` and `f [[Resolver f]]` is necessary.

Please see my code [share Resolver](https://github.com/Lupino/dispatch-share/blob/master/src/Share/GraphQL.hs#L36)

The `share` is an `object` load from `ShareM`, it needed `f [Resolver f]`.

That `share` has `children` the children is an array load from `ShareM`, it needed `f [[Resolver f]]`

**Comment by jdnavarro** [comment]
OK, I think I can get the idea now why you need the wrapping but I suspect it may be possible to write your example with functions that don't use wrapped arguments.

Please, give me a few days to play with your code a bit more, if I can't find a solution, we can replace all the current unwrapped versions with the wrapped ones.

**Comment by jdnavarro** [comment]
I don't find the time to work out the example you provided so I merged it as it is for now. Just keep in mind that I'll try to revisit this example in the future and try to get rid of the `'` functions.

**Comment by Lupino** [comment]
Think you.

**Pull request merged**
