### PR TITLE
All improvements

### PR DESCRIPTION
**Pull request by solrun**
This pull request includes all the improvements from the other three pull requests, for easier merging. It also updates the tutorial based on how the `error-handling` branch changes the output of the data and handles errors.

### CODE REVIEW

**Comment by Tritlo** [comment]
If this is accepted, I would close the other pull requests.

**Comment by jdnavarro** [comment]
Wow, these are actually important contributions. I'll need to make some modifications to the exceptions part and squash some commits. If you are in a hurry you can help me by rebasing your branch, many commits related to documentation can be put together, but I can do that myself I it's too much trouble for you.

**Comment by Tritlo** [comment]
Hmm, the build seems to fail due to travis not being able to reach `ppa.launchpad.net`

**Comment by jdnavarro** [comment]
I mainly added haddock links to the documentation but overall I left it as you submitted. To be honest, I'm still not entirely convinced about the API for error handling, but since I might not have time in the near future to come up with an improved API, I left yours intact because it does the job just fine. Just be aware that I might change the API for error handling quite drastically in the future.

As soon as I finish porting the end-to-end tests I'll make a release including this PR. Would you like to be listed as authors of the package?

Thank you very much for your contribution!

**Comment by solrun** [comment]
Yes, we'd love to be listed as authors if you'll have us.

We've been thinking about the error api, and a monad based one would
probably work as well, seeing as monads are now also applicative. We made
an attempt at a monad approach originally, but shied away from adding a
monad constraint, since we thought it was more of an aggressive rewrite.
You can view [the attempt here](
https://github.com/solrun/graphql-haskell/commit/8903ace402520a62289ea445ece4d0bf2df3cba6).
It uses monad transformers and adds a dependecy on the mtl library, but
works pretty well.

Thanks for accepting our pull request, it's great to be able to contribute!

Cheers,
Sólrún and Matti

**Comment by jdnavarro** [comment]
@solrun, I saw your previous attempt with monad transformers but liked more your latter approach. I'd like the API to be approachable for people who are familiar with GraphQL but not necessarily with Haskell. Bringing monad transformers would raise the Haskell expertise bar, so if it's possible to avoid them I think we should, even though it may be unavoidable to introduce them as more functionality is added.

@solrun @Tritlo, please have a look at the new [AUTHORS.md](https://github.com/jdnavarro/graphql-haskell/blob/authors/AUTHORS.md) file I created and modify it as you see fit before I merge into `master`.

**Comment by Tritlo** [comment]
Alright. Is it all right if we add ourselves to the authors part of the cabal file as well?

**Pull request merged**
